"""SQLAlchemy ORM models.

Phase 1: persistence layer structure. Phase 6.1: reshaped for the service —
the schema is now owned by Alembic (`sawti/db/migrations`), not
`Base.metadata.create_all()`. A model change here needs a migration.

Note on identity: `Agent` here is a contact-center-agent record that calls
and rubric scores attach to for reporting — it is not a login/account and
has no credentials. The only authenticating identity anywhere in this
system is the QA reviewer, captured on `ReviewerAction` /
`sawti.schemas.Correction`. Do not add auth/permissions fields to `Agent`.
"""

from __future__ import annotations

import uuid
from datetime import datetime
from typing import Any

from sqlalchemy import DateTime, Float, ForeignKey, Integer, String, Text, UniqueConstraint, text
from sqlalchemy import Enum as SAEnum
from sqlalchemy.dialects.postgresql import JSONB
from sqlalchemy.dialects.postgresql import UUID as PGUUID
from sqlalchemy.orm import DeclarativeBase, Mapped, mapped_column, relationship

from sawti.schemas import CallStatus

#: Tables created and versioned by `langgraph-checkpoint-postgres`'s own
#: `setup()` (see `sawti.db.checkpointer`), not by Alembic.
CHECKPOINT_TABLES = frozenset(
    {"checkpoints", "checkpoint_blobs", "checkpoint_writes", "checkpoint_migrations"}
)

#: CHECK constraints generated by non-native `SAEnum` columns. Alembic reflects
#: them from the database but cannot see them on the model side, so without
#: this it reports each as a constraint to drop.
_ENUM_CHECK_CONSTRAINTS = frozenset({"call_status"})


def alembic_include_object(obj: Any, name: str | None, type_: str, reflected: bool, compare_to: Any) -> bool:
    """Alembic `include_object` hook: what autogenerate compares against `Base.metadata`.

    Excludes LangGraph's checkpoint tables (owned by the library, so every
    `--autogenerate` would otherwise propose dropping them) and the enum
    CHECK constraints above (a known false positive).
    """
    if type_ == "table" and name in CHECKPOINT_TABLES:
        return False
    return not (type_ == "check_constraint" and reflected and name in _ENUM_CHECK_CONSTRAINTS)


class Base(DeclarativeBase):
    """Declarative base for all Sawti ORM models."""


class Agent(Base):
    """A contact-center agent record. Not a login — has no credentials.

    Calls and rubric scores attach to this record for reporting purposes only.
    """

    __tablename__ = "agents"

    id: Mapped[uuid.UUID] = mapped_column(PGUUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    name: Mapped[str] = mapped_column(String(255), nullable=False)
    external_id: Mapped[str | None] = mapped_column(String(255), nullable=True, unique=True)
    created_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), nullable=False)


class Call(Base):
    """A single contact-center call and its metadata.

    Only the *redacted* transcript is ever stored. The API redacts at the
    boundary and discards the raw text, so it is not recoverable from here —
    a deliberate trade, see `docs/09-DECISIONS.md` (2026-10-06, redaction at
    the API boundary).
    """

    __tablename__ = "calls"

    id: Mapped[uuid.UUID] = mapped_column(PGUUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    agent_id: Mapped[uuid.UUID] = mapped_column(PGUUID(as_uuid=True), ForeignKey("agents.id"), nullable=False)
    audio_path: Mapped[str | None] = mapped_column(String(1024), nullable=True)
    redacted_transcript: Mapped[str | None] = mapped_column(Text, nullable=True)
    language: Mapped[str] = mapped_column(String(16), nullable=False)
    occurred_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), nullable=False)
    # A VARCHAR + CHECK constraint, not a native Postgres ENUM: adding a value
    # later is a constraint swap instead of an `ALTER TYPE`, and downgrade has
    # no type object to drop. See `CallStatus` for the mapping to the graph's
    # own `ReviewStatus`.
    status: Mapped[CallStatus] = mapped_column(
        SAEnum(
            CallStatus,
            name="call_status",
            native_enum=False,
            create_constraint=True,
            length=32,
            values_callable=lambda enum: [member.value for member in enum],
        ),
        nullable=False,
        default=CallStatus.QUEUED,
        server_default=CallStatus.QUEUED.value,
    )
    # Latency instrumentation. queue wait = started_at - queued_at; processing
    # = finished_at - started_at. `finished_at` marks the end of the *analysis*
    # task (completed, interrupted for review, or failed), not of human review.
    queued_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)
    started_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)
    finished_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)
    # How many PII spans `redact()` replaced. The count only — never the values.
    pii_redacted_count: Mapped[int] = mapped_column(Integer, nullable=False, default=0, server_default="0")
    # How many times the analysis task claimed this call. >1 means it was
    # retried after a transient provider error; the source of the retry rate.
    attempts: Mapped[int] = mapped_column(Integer, nullable=False, default=0, server_default="0")
    # When a message for this call was last put on the queue (submission, a
    # retry, or the reaper). The reaper keys on it, not `queued_at`, so a
    # healthy backlog is not re-enqueued over and over.
    enqueued_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)

    agent: Mapped[Agent] = relationship()


class CallAnalysisRecord(Base):
    """Persisted `sawti.schemas.CallAnalysis` output for a call, plus review-screen context.

    `payload` is exactly `CallAnalysis.model_dump(mode="json")` and nothing
    else, so `CallAnalysis.model_validate(record.payload)` always round-trips.
    What the review screen needs beyond the analysis lives in its own columns
    (see `docs/09-DECISIONS.md`, 2026-10-06, review-screen fields). Those are
    nullable because not every record comes from a service graph run — the
    phase 4/5 scripts persist bare analyses through
    `sawti.memory.capture.persist_analysis_record`.
    """

    __tablename__ = "call_analyses"
    __table_args__ = (UniqueConstraint("call_id", name="uq_call_analyses_call_id"),)

    id: Mapped[uuid.UUID] = mapped_column(PGUUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    call_id: Mapped[uuid.UUID] = mapped_column(PGUUID(as_uuid=True), ForeignKey("calls.id"), nullable=False)
    payload: Mapped[dict[str, object]] = mapped_column(JSONB, nullable=False)
    confidence: Mapped[float] = mapped_column(nullable=False)
    requires_human_review: Mapped[bool] = mapped_column(nullable=False)
    created_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), nullable=False)

    # --- Review-screen context ---
    grounding_coverage: Mapped[float | None] = mapped_column(Float, nullable=True)
    # The threshold in force for *this* run. It is read from settings on every
    # run, so it can change between runs; the screen must show the one used.
    confidence_threshold: Mapped[float | None] = mapped_column(Float, nullable=True)
    # Short human-readable "why a human is looking at this", or None when the
    # call auto-passed.
    escalation_reason: Mapped[str | None] = mapped_column(Text, nullable=True)
    # Claims `ground` dropped, as the model proposed them (attempted quote
    # included). A JSON list.
    rejected_claims: Mapped[list[Any]] = mapped_column(
        JSONB, nullable=False, default=list, server_default=text("'[]'::jsonb")
    )
    # `MemoryRule.id`s retrieved for this run, best match first, as strings.
    retrieved_rule_ids: Mapped[list[Any]] = mapped_column(
        JSONB, nullable=False, default=list, server_default=text("'[]'::jsonb")
    )

    call: Mapped[Call] = relationship()


class ReviewerAction(Base):
    """A persisted `sawti.schemas.Correction` — the only authenticated identity in this system."""

    __tablename__ = "reviewer_actions"

    id: Mapped[uuid.UUID] = mapped_column(PGUUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    call_analysis_id: Mapped[uuid.UUID] = mapped_column(
        PGUUID(as_uuid=True), ForeignKey("call_analyses.id"), nullable=False
    )
    reviewer_id: Mapped[str] = mapped_column(String(255), nullable=False)
    payload: Mapped[dict[str, object]] = mapped_column(JSONB, nullable=False)
    created_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), nullable=False)
    # The review submission this correction came from (phase 6.2). Null for
    # corrections captured outside the service (the phase 4/5 scripts).
    review_submission_id: Mapped[uuid.UUID | None] = mapped_column(
        PGUUID(as_uuid=True),
        ForeignKey("review_submissions.id", name="fk_reviewer_actions_review_submission_id"),
        nullable=True,
    )
    # Set once `sawti.memory.persistence.induce_and_store` has handled this
    # correction (phase 6.2): induction runs at most once per correction, and
    # an interrupted backfill resumes where it stopped. Outcome is
    # "inserted" (a rule was stored) or "conflict" (the candidate contradicted
    # an existing rule and was left for a human, as `insert_rule` decides).
    induced_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)
    induction_outcome: Mapped[str | None] = mapped_column(String(16), nullable=True)

    call_analysis: Mapped[CallAnalysisRecord] = relationship()


class ReviewSubmission(Base):
    """One reviewer's complete verdict set for one escalated analysis (phase 6.2).

    Holds what `Correction` cannot: a verdict for *every* grounded claim,
    `confirm` included. Each `reject` / `correct` verdict also becomes a
    `Correction` (a `ReviewerAction` row linked back here), so the phase 4/5
    code that reads `ReviewerAction` keeps working unchanged. See
    docs/09-DECISIONS.md, 2026-10-07, review submissions.

    One per analysis: the graph is resumed exactly once, so a second
    submission would be a verdict nothing acts on.
    """

    __tablename__ = "review_submissions"

    id: Mapped[uuid.UUID] = mapped_column(PGUUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    call_analysis_id: Mapped[uuid.UUID] = mapped_column(
        PGUUID(as_uuid=True), ForeignKey("call_analyses.id"), nullable=False, unique=True
    )
    reviewer_id: Mapped[str] = mapped_column(String(255), nullable=False)
    # `sawti.api.schemas.ReviewSubmission.model_dump(mode="json")`.
    verdicts: Mapped[dict[str, Any]] = mapped_column(JSONB, nullable=False)
    created_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), nullable=False)


class MemoryRuleRecord(Base):
    """A persisted `sawti.memory.rule_schema.MemoryRule` (phase 6.2).

    Before this, rules only ever lived in an in-process `MemoryStore`. The
    worker rebuilds its store from the active rows here, and the review
    screen resolves `call_analyses.retrieved_rule_ids` to text through this
    table. Rules are injected into prompts, so `rule_text` must be redacted
    text only.
    """

    __tablename__ = "memory_rules"

    id: Mapped[uuid.UUID] = mapped_column(PGUUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    rule_text: Mapped[str] = mapped_column(Text, nullable=False)
    source_correction_ids: Mapped[list[Any]] = mapped_column(
        JSONB, nullable=False, default=list, server_default=text("'[]'::jsonb")
    )
    created_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), nullable=False)
    success_count: Mapped[int] = mapped_column(Integer, nullable=False, default=0, server_default="0")
    failure_count: Mapped[int] = mapped_column(Integer, nullable=False, default=0, server_default="0")
    retired: Mapped[bool] = mapped_column(nullable=False, default=False, server_default=text("false"))
